version: "3"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/code/app
    tty: true
    ports:
      - "8080-8081:8080"
    deploy:
      replicas: 2
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    #    working_dir: /app
    volumes:
      - ./frontend/app:/app
    tty: true
    ports:
      - "5173:5173"
